// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVFGtHueDHqQ0siCL4qMlmOwpUFkZutUk',
    appId: '1:844473077697:web:ac6f9237859dd15f416940',
    messagingSenderId: '844473077697',
    projectId: 'trafficsolution-395806',
    authDomain: 'trafficsolution-395806.firebaseapp.com',
    storageBucket: 'trafficsolution-395806.appspot.com',
    measurementId: 'G-C5Q88TD5Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFGtHueDHqQ0siCL4qMlmOwpUFkZutUk',
    appId: '1:844473077697:android:93fb2d9b759260d1416940',
    messagingSenderId: '844473077697',
    projectId: 'trafficsolution-395806',
    storageBucket: 'trafficsolution-395806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUkhe92uHnbl8UKNN9AB0ZfqQOyjGoYtU',
    appId: '1:844473077697:ios:7e9264980a8c1f9e416940',
    messagingSenderId: '844473077697',
    projectId: 'trafficsolution-395806',
    storageBucket: 'trafficsolution-395806.appspot.com',
    androidClientId: '844473077697-8c5kc5qbm0tr9a4i8gfv3dhm16g6tpt2.apps.googleusercontent.com',
    iosClientId: '844473077697-s2fj3ed5edqolcl7csa65v4s2jc2jec0.apps.googleusercontent.com',
    iosBundleId: 'com.example.trafficSolutionDsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUkhe92uHnbl8UKNN9AB0ZfqQOyjGoYtU',
    appId: '1:844473077697:ios:9f776b0d17941915416940',
    messagingSenderId: '844473077697',
    projectId: 'trafficsolution-395806',
    storageBucket: 'trafficsolution-395806.appspot.com',
    androidClientId: '844473077697-8c5kc5qbm0tr9a4i8gfv3dhm16g6tpt2.apps.googleusercontent.com',
    iosClientId: '844473077697-4q5j8978fvg6b1un6jgaudr3m7a9c59s.apps.googleusercontent.com',
    iosBundleId: 'com.example.trafficSolutionDsc.RunnerTests',
  );
}
